### ISSUE TITLE
Add support for required, minimum and maximum selected items

### ISSUE THREAD

**Issue by dotpointer** [Neovici/paper-autocomplete-chips#24]
This component needs support for the standard required property so it can stop form validation if it is not filled in. It seems like the required attribute is not available at all in the component.

In addition to this it would be good if a maximum or a minimum amount of selected items could be defined too, like max-selected-items="2" and min-selected-items="5". The defaults for these could be 0, but setting required would internally override min-selected-items=0 to min-selected-items=1.

For example, required could be set on the component and there could be a minimum of 3 but a maximum of 5 items allowed to be selected.

This issue affects Redmine issue 18951 concerning supplier address and contact handling.

**Comment by megheaiulian** [comment]
@dotpointer  According to the iron-form [docs](https://www.webcomponents.org/element/PolymerElements/iron-form) the element need to have a `name`, `value` and `validate` function defined to work correctly with `iron-form` validation.

**Comment by dotpointer** [comment]
@megheaiulian This is the way it is used in the data entry dialog used in 18951:

`<paper-autocomplete-chips
	id="autocomplete" class="autocomplete-field"
	source="[[ field.options ]]"
	text-property="label"
	label="[[ field.label ]]"
	show-results-on-focus
	selected-items="{{ field.value }}">
</paper-autocomplete-chips>`

Should it be changed to enable validation of it?

**Comment by megheaiulian** [comment]
It needs name and value attributes

**Comment by dotpointer** [comment]
Tried adding name and value attribute without any effect:

```
<paper-autocomplete-chips
	id="autocomplete" class="autocomplete-field"
	name="x"
	required="[[ field.required ]]"
	value="{{ field.value }}"
	source="[[ field.options ]]"
	text-property="label"
	label="[[ field.label ]]"
	show-results-on-focus
	selected-items="{{ field.value }}">
</paper-autocomplete-chips>
```

But If I set only required="[[ field.required ]]" and inside the paper-autocomplete-chips add required="[[ required ]]" to the <paper-autocomplete> plus add required: { type: Boolean } to the properties, then it stops the validation if the paper-autocomplete inside is not filled in.

**Comment by megheaiulian** [comment]
Maybe try this:
```
<paper-autocomplete-chips
	id="autocomplete" class="autocomplete-field"
	name$="x"
	required="[[ field.required ]]"
	value="{{ field.value }}"
	source="[[ field.options ]]"
	text-property="label"
	label="[[ field.label ]]"
	show-results-on-focus
	selected-items="{{ field.value }}"
       value$="[[ field.value ]]"
>
</paper-autocomplete-chips>
```

**Comment by dotpointer** [comment]
Tried it, still does not validate and stop if empty.

**Comment by megheaiulian** [comment]
Try adding also required$="".

**Comment by dotpointer** [comment]
Tried both required$="[[ field.required ]]" and required$="" added to the end of the attributes, no effect.

The value property does not seem to get written inside the component, it is only read, if it is valueProperty:

```
/**
	* `source` item value property to store in `selectedItems`
	* if empty, use the whole object
	*/
valueProperty: {
	type: String,
	value: 'value'
},
```

**Comment by dotpointer** [comment]
There is no validate function inside the component. 

If I add one and return false, then it stops the validation, no additional attributes seems required, not even required:

```
validate() {
	return false;
}
```
But it does not display any error message in red and does not care about required. I have tried add errorMessage and errorMessageProperty text properties, but it does not read these.

**Comment by dotpointer** [comment]
Because this is a custom element, maybe the error text container itself needs to be added inside the component. validate() -> false only tells the validation is invalid.

**Comment by dotpointer** [comment]
The following suggestion makes it validate and display red error borders around the paper-autocomplete when nothing is selected:

```
<paper-autocomplete ...  required="[[ acRequired ]]" ...>

...

properties: {
	acRequired: {
		type: Boolean,
		value: false
	},
}
observers: [
	'selectedItemsObserver(selectedItems.*)'
],

...

selectedItemsObserver(selectedItemsNotify) {
	this.set('acRequired', selectedItemsNotify.base.length < 1);
	console.log('acRequired is now: ', this.acRequired);
},

...

validate() {
	this.$.ac.validate();
	return false;
}
```

**Comment by dotpointer** [comment]
There is a pending fix for this in #25.

**Comment by nomego** [comment]
Solved @dotpointer ?

**Comment by dotpointer** [comment]
@nomego Yes, the pull request to fix this has been merged.

**Comment by dotpointer** [comment]
Closing this.
