### ISSUE TITLE
Polymer 3 Support

### ISSUE THREAD

**Issue by dhruvp-8** [Neovici/paper-autocomplete-chips#34]
When will you be rolling out Polymer 3 support for this component? It would be nice to have this component on npm.

**Comment by dhruvp-8** [comment]
Thanks, I will try to implement it and keep you in the loop.

**Comment by nomego** [comment]
We expect Polymer 3 support to be shipped this week or next, if you're still using it :)

**Comment by cristinecula** [comment]
Dependencies:

[x] iron-icon
https://www.webcomponents.org/element/@polymer/iron-icon
[ ] paper-autocomplete
Not upgraded to Polymer 3, but a fork exists here: https://github.com/communitybuilders/paper-autocomplete/tree/verdaccio
[ ] cosmoz-i18next https://github.com/Neovici/cosmoz-i18next/issues/18
