### ISSUE TITLE
Sanitize RegExp input when highlighting suggestions

### ISSUE THREAD

**Issue by nomego** [Neovici/paper-autocomplete-chips#35]
Errors such as:
`Uncaught SyntaxError: Invalid regular expression: /(seb (ag)***använd 1560 (1578_54774245))/: Nothing to repeat`

could happen due to:
https://github.com/Neovici/paper-autocomplete-chips/blob/ad329759ae63d51ab67a09f31b8d73832e1a7080/paper-autocomplete-chips.html#L258

**Comment by dotpointer** [comment]
Use https://www.npmjs.com/package/escape-string-regexp ?

**Comment by nomego** [comment]
Fixed by #36
